# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Angel.AudioAuditor
PackageVersion: 1.7.0
InstallerLocale: en-US
InstallerType: portable
InstallModes:
  - silent
  - silentWithProgress
  - interactive
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Angel2mp3/AudioAuditor/releases/download/v1.7.0/AudioAuditor.exe
    InstallerSha256: 2B5BD0AB00299234050A3F7627581C7E4035D20F21495FBB124C151E7D0B1A76
    Commands:
      - AudioAuditor
    InstallScope: user
ManifestType: installer
ManifestVersion: 1.6.0
