using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using TagLib;

namespace AudioQualityChecker.Services
{
    /// <summary>
    /// Detects verifiable AI watermarks and metadata signatures embedded by
    /// AI music generation services (Suno, Udio, AIVA, Boomy, etc.).
    ///
    /// Detection methods (verifiable evidence ONLY):
    ///   1. Metadata tag scanning — known AI service markers in ID3v2, Vorbis, APE, MP4 tags
    ///   2. Raw byte pattern scanning — AI service identifiers embedded in file headers/trailers
    ///   3. C2PA / Content Credentials — provenance manifest markers
    ///   4. Known custom chunks/atoms — service-specific embedded data
    ///
    /// This detector does NOT use heuristic or statistical methods (spectral analysis,
    /// fingerprinting, etc.). It only flags files with concrete, verifiable evidence.
    /// </summary>
    public static class AiWatermarkDetector
    {
        // ══════════════════════════════════════════════════════════════
        //  Known AI service metadata markers
        // ══════════════════════════════════════════════════════════════

        private static readonly string[] AiMetaMarkers =
        {
            // AI music generation services — use specific identifiers only
            "suno.ai", "suno.com",
            "udio.com",
            "soundraw.io",
            "aiva.ai",
            "boomy.com",
            "amper music", "shutterstock ai",
            "loudly.com",
            "beatoven.ai",
            "mubert.com",
            "stable audio", "stability.ai",
            "riffusion",
            "musiclm", "musicgen", "audiogen",
            "openai jukebox",

            // AI generation indicators (only explicit statements)
            "ai-generated", "ai_generated",
            "generated by ai", "created by ai", "made by ai",

            // AI watermarking systems
            "audioseal", "audio_seal", "audio seal",
            "synthid", "synth_id", "synth id",
            "wavmark", "wav_mark",

            // Content provenance / credentials (require full phrase)
            "content credentials", "contentcredentials",
            "contentauthenticity", "content authenticity",
            "cai manifest",
        };

        // Specific metadata field names that AI services use
        private static readonly string[] AiTagFieldNames =
        {
            "ai_generated", "ai-generated", "is_ai",
            "generation_model", "generation-model",
            "ai_model", "ai-model", "model_name",
            "ai_source", "ai-source", "ai_service",
            "generated_by", "generated-by",
            "ai_watermark", "watermark_type",
            "c2pa.actions", "c2pa.claim",
            "content_credentials",
            "synthesis_tool", "synthesis-tool",
            "prompt", "generation_prompt",
        };

        // Known non-AI software/encoders to exclude (prevents false positives)
        private static readonly string[] KnownNonAiSoftware =
        {
            "audacity", "adobe audition", "fl studio", "ableton",
            "pro tools", "logic pro", "cubase", "reaper", "garageband",
            "studio one", "bitwig", "lmms", "ardour", "cakewalk",
            "bandlab", "soundforge", "wavelab", "izotope", "ozone",
            "ffmpeg", "lame", "libvorbis", "libopus", "libflac",
            "mediamonkey", "foobar2000", "musicbee", "winamp",
            "itunes", "xld", "dbpoweramp", "exact audio copy",
            "freac", "sox", "goldwave", "ocenaudio", "wavepad",
            "nero", "cdex", "audiograbber",
            // Streaming rippers/downloaders
            "streamrip", "deemix", "spotify", "tidal",
        };

        // Raw byte patterns to search for in file data.
        // Only patterns >= 8 bytes to avoid false positives from random audio data.
        private static readonly byte[][] RawBytePatterns =
        {
            // Content Credentials (18 bytes — safe from random matches)
            Encoding.ASCII.GetBytes("contentcredentials"),
            // AudioSeal watermark identifier (9 bytes)
            Encoding.ASCII.GetBytes("audioseal"),
        };

        // Text patterns to search for in raw file header/trailer bytes.
        // Only patterns long enough (>= 7 chars) to avoid random matches in audio data.
        private static readonly string[] RawTextPatterns =
        {
            "suno.ai", "udio.com", "soundraw.io",
            "aiva.ai", "boomy.com", "mubert.com",
            "beatoven.ai", "stability.ai", "loudly.com",
            "audioseal", "synthid",
            "contentcredentials",
            "riffusion", "musicgen", "audiogen",
        };

        // ══════════════════════════════════════════════════════════════
        //  Public API
        // ══════════════════════════════════════════════════════════════

        public class AiDetectionResult
        {
            public bool IsAiDetected { get; set; }
            public List<string> Sources { get; set; } = new();
            public string Summary { get; set; } = "";
            /// <summary>
            /// Confidence level: 0.0–1.0. Higher values indicate stronger evidence.
            /// Only flagged as AI when confidence >= 0.5 (strong match) or multiple markers found.
            /// </summary>
            public double Confidence { get; set; }
        }

        /// <summary>
        /// Scans an audio file for verifiable AI watermarks and metadata signatures.
        /// Returns detection result with found evidence.
        /// </summary>
        public static AiDetectionResult Detect(string filePath)
        {
            var result = new AiDetectionResult();
            var foundMarkers = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var encoderInfo = new List<string>(); // track encoder/software for false-positive filtering

            // ── Check 1: Metadata tags ──
            try
            {
                ScanMetadataTags(filePath, foundMarkers, encoderInfo);
            }
            catch { /* metadata scan is best-effort */ }

            // ── Check 2: Raw byte patterns in file ──
            try
            {
                ScanRawBytes(filePath, foundMarkers);
            }
            catch { /* raw scan is best-effort */ }

            // ── False-positive filtering ──
            // If the file was created by a known DAW/encoder, remove weak generic markers
            bool hasKnownEncoder = encoderInfo.Any(enc =>
                KnownNonAiSoftware.Any(sw => enc.Contains(sw, StringComparison.OrdinalIgnoreCase)));

            if (hasKnownEncoder)
            {
                // Only keep strong AI-specific markers (named services, watermark systems)
                var strongMarkers = foundMarkers.Where(m => IsStrongAiMarker(m)).ToHashSet(StringComparer.OrdinalIgnoreCase);
                foundMarkers = strongMarkers;
            }

            // ── Confidence scoring ──
            double confidence = CalculateConfidence(foundMarkers);

            // ── Build result — require confidence threshold ──
            // Threshold 0.5 means at least one strong marker or 3+ weak markers
            if (foundMarkers.Count > 0 && confidence >= 0.5)
            {
                result.IsAiDetected = true;
                result.Sources = foundMarkers.ToList();
                result.Confidence = confidence;
                result.Summary = string.Join(", ", foundMarkers.Take(3));
                if (foundMarkers.Count > 3)
                    result.Summary += $" (+{foundMarkers.Count - 3} more)";
            }

            return result;
        }

        /// <summary>
        /// Returns true if this marker is a strong indicator (named AI service or watermark system),
        /// not just a generic phrase like "AI Generated" that could be user-added.
        /// </summary>
        private static bool IsStrongAiMarker(string marker)
        {
            var strong = new[] {
                "Suno", "Udio", "Soundraw", "AIVA", "Boomy", "Amper", "Loudly",
                "Beatoven", "Mubert", "Stable Audio", "Riffusion", "MusicLM",
                "MusicGen", "AudioGen", "Jukebox",
                "AudioSeal", "SynthID", "WavMark", "Content Credentials",
                "Content Authenticity"
            };
            return strong.Any(s => marker.Contains(s, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// Calculates a confidence score (0.0–1.0) based on number and type of markers found.
        /// </summary>
        private static double CalculateConfidence(HashSet<string> markers)
        {
            if (markers.Count == 0) return 0;

            double score = 0;
            foreach (var m in markers)
            {
                if (IsStrongAiMarker(m))
                    score += 0.5; // strong evidence
                else
                    score += 0.2; // weak/generic evidence
            }

            return Math.Min(score, 1.0);
        }

        // ══════════════════════════════════════════════════════════════
        //  Metadata Tag Scanning
        // ══════════════════════════════════════════════════════════════

        private static void ScanMetadataTags(string filePath, HashSet<string> found, List<string>? encoderInfo = null)
        {
            using var tagFile = TagLib.File.Create(filePath);
            if (tagFile?.Tag == null) return;

            // Collect all tag text into a single searchable string
            var allTagText = new StringBuilder(2048);

            // ── Collect encoder/software info for false-positive filtering ──
            encoderInfo ??= new List<string>();
            // TagLib properties.Codecs can tell us about encoder
            try
            {
                foreach (var codec in tagFile.Properties.Codecs)
                {
                    if (codec != null)
                        encoderInfo.Add(codec.Description ?? "");
                }
            }
            catch { }

            // ── General tag fields ──
            AppendIfNotEmpty(allTagText, "comment", tagFile.Tag.Comment);
            AppendIfNotEmpty(allTagText, "copyright", tagFile.Tag.Copyright);
            AppendIfNotEmpty(allTagText, "description", tagFile.Tag.Description);
            AppendIfNotEmpty(allTagText, "conductor", tagFile.Tag.Conductor);
            AppendIfNotEmpty(allTagText, "grouping", tagFile.Tag.Grouping);

            if (tagFile.Tag.Performers != null)
                foreach (var p in tagFile.Tag.Performers)
                    AppendIfNotEmpty(allTagText, "performer", p);

            if (tagFile.Tag.AlbumArtists != null)
                foreach (var a in tagFile.Tag.AlbumArtists)
                    AppendIfNotEmpty(allTagText, "albumartist", a);

            if (tagFile.Tag.Composers != null)
                foreach (var c in tagFile.Tag.Composers)
                    AppendIfNotEmpty(allTagText, "composer", c);

            if (tagFile.Tag.Genres != null)
                foreach (var g in tagFile.Tag.Genres)
                    AppendIfNotEmpty(allTagText, "genre", g);

            // ── ID3v2 specific frames ──
            if (tagFile.GetTag(TagTypes.Id3v2) is TagLib.Id3v2.Tag id3)
            {
                // User-defined text frames (TXXX) - most common place for AI markers
                foreach (var frame in id3.GetFrames<TagLib.Id3v2.UserTextInformationFrame>())
                {
                    string desc = frame.Description ?? "";
                    string val = frame.Text?.Length > 0 ? string.Join(" ", frame.Text) : "";

                    // Check if the field NAME itself is an AI indicator
                    foreach (var fieldName in AiTagFieldNames)
                    {
                        if (desc.Contains(fieldName, StringComparison.OrdinalIgnoreCase))
                        {
                            found.Add($"Tag:{desc}={val}");
                        }
                    }

                    AppendIfNotEmpty(allTagText, desc, val);
                }

                // User-defined URL frames (WXXX)
                foreach (var frame in id3.GetFrames<TagLib.Id3v2.UserUrlLinkFrame>())
                {
                    var urlText = frame.Text != null ? string.Join(" ", frame.Text) : "";
                    AppendIfNotEmpty(allTagText, frame.Description ?? "url", urlText);
                }

                // Comment frames (COMM)
                foreach (var frame in id3.GetFrames<TagLib.Id3v2.CommentsFrame>())
                {
                    AppendIfNotEmpty(allTagText, "comment", frame.Text ?? "");
                    AppendIfNotEmpty(allTagText, "comment_desc", frame.Description ?? "");
                }

                // Standard text frames
                foreach (var frame in id3.GetFrames<TagLib.Id3v2.TextInformationFrame>())
                {
                    string val = frame.Text?.Length > 0 ? string.Join(" ", frame.Text) : "";
                    AppendIfNotEmpty(allTagText, frame.FrameId.ToString(), val);
                }
            }

            // ── Xiph/Vorbis comments (FLAC, OGG, OPUS) ──
            if (tagFile.GetTag(TagTypes.Xiph) is TagLib.Ogg.XiphComment xiph)
            {
                // Check known AI-related field names
                foreach (var fieldName in AiTagFieldNames)
                {
                    var values = xiph.GetField(fieldName);
                    if (values != null && values.Length > 0)
                    {
                        foreach (var val in values)
                        {
                            found.Add($"Tag:{fieldName}={val}");
                            AppendIfNotEmpty(allTagText, fieldName, val);
                        }
                    }
                }

                // Also check common fields
                string[] commonFields = { "ENCODER", "COMMENT", "DESCRIPTION", "SOURCE",
                    "TOOL", "SOFTWARE", "GENERATOR", "CREATED_BY", "PRODUCER" };
                foreach (var fieldName in commonFields)
                {
                    var values = xiph.GetField(fieldName);
                    if (values != null && values.Length > 0)
                    {
                        foreach (var val in values)
                            AppendIfNotEmpty(allTagText, fieldName, val);
                    }
                }
            }

            // ── APE tags ──
            if (tagFile.GetTag(TagTypes.Ape) is TagLib.Ape.Tag ape)
            {
                // APE tag doesn't have a direct "iterate all items" in TagLibSharp,
                // but we can check known AI fields
                foreach (var fieldName in AiTagFieldNames)
                {
                    var item = ape.GetItem(fieldName);
                    if (item != null)
                    {
                        found.Add($"Tag:{fieldName}={item}");
                    }
                }
            }

            // ── Apple/MP4 tags ──
            if (tagFile.GetTag(TagTypes.Apple) is TagLib.Mpeg4.AppleTag apple)
            {
                // Check the ©too (encoding tool) atom
                var toolAtom = apple.DataBoxes("©too");
                foreach (var box in toolAtom)
                {
                    AppendIfNotEmpty(allTagText, "encoding_tool", box.Text ?? "");
                }

                // Check ©cmt (comment)
                var cmtAtom = apple.DataBoxes("©cmt");
                foreach (var box in cmtAtom)
                {
                    AppendIfNotEmpty(allTagText, "comment", box.Text ?? "");
                }

                // Check ©des (description)
                var desAtom = apple.DataBoxes("©des");
                foreach (var box in desAtom)
                {
                    AppendIfNotEmpty(allTagText, "description", box.Text ?? "");
                }

                // Check free-form atoms that AI services might use
                string[] freeFormKeys = { "AI_GENERATED", "AI_SOURCE", "GENERATOR", "CREATED_BY", "SYNTHESIS_TOOL" };
                foreach (var key in freeFormKeys)
                {
                    try
                    {
                        var boxes = apple.DataBoxes("----:com.apple.iTunes:" + key);
                        foreach (var box in boxes)
                        {
                            if (!string.IsNullOrEmpty(box.Text))
                            {
                                found.Add($"Atom:{key}={box.Text}");
                                AppendIfNotEmpty(allTagText, key, box.Text);
                            }
                        }
                    }
                    catch { }
                }
            }

            // ── Collect encoder info from common encoder tag fields ──
            string[] encoderFields = { "ENCODER", "TOOL", "SOFTWARE", "ENCODED_BY", "ENCODING", "TSSE" };
            if (tagFile.GetTag(TagTypes.Xiph) is TagLib.Ogg.XiphComment xiphEnc)
            {
                foreach (var ef in encoderFields)
                {
                    var vals = xiphEnc.GetField(ef);
                    if (vals != null)
                        foreach (var v in vals)
                            if (!string.IsNullOrWhiteSpace(v)) encoderInfo.Add(v);
                }
            }
            if (tagFile.GetTag(TagTypes.Id3v2) is TagLib.Id3v2.Tag id3Enc)
            {
                // TSSE = Software/Hardware and settings used for encoding
                foreach (var frame in id3Enc.GetFrames<TagLib.Id3v2.TextInformationFrame>())
                {
                    string fid = frame.FrameId.ToString();
                    if (fid == "TSSE" || fid == "TENC")
                    {
                        string val = frame.Text?.Length > 0 ? string.Join(" ", frame.Text) : "";
                        if (!string.IsNullOrWhiteSpace(val)) encoderInfo.Add(val);
                    }
                }
            }

            // ── Now search all collected text for AI markers ──
            string fullText = allTagText.ToString().ToLowerInvariant();

            foreach (var marker in AiMetaMarkers)
            {
                if (fullText.Contains(marker, StringComparison.OrdinalIgnoreCase))
                {
                    // Determine which service it matches
                    string source = CategorizeMarker(marker);
                    if (!string.IsNullOrEmpty(source))
                        found.Add(source);
                }
            }
        }

        // ══════════════════════════════════════════════════════════════
        //  Raw Byte Pattern Scanning
        // ══════════════════════════════════════════════════════════════

        private static void ScanRawBytes(string filePath, HashSet<string> found)
        {
            var fi = new FileInfo(filePath);
            if (!fi.Exists || fi.Length == 0) return;

            // Read first 64KB and last 64KB for embedded markers.
            // Do NOT scan middle of file — it's raw audio data whose bytes
            // interpreted as ASCII produce false text matches.
            int headTailSize = (int)Math.Min(65536, fi.Length);

            byte[] headBytes;
            byte[] tailBytes;

            using (var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read))
            {
                headBytes = new byte[headTailSize];
                int headRead = fs.Read(headBytes, 0, headTailSize);
                if (headRead < headTailSize)
                    Array.Resize(ref headBytes, headRead);

                if (fi.Length > headTailSize * 2)
                {
                    fs.Seek(-headTailSize, SeekOrigin.End);
                    tailBytes = new byte[headTailSize];
                    int tailRead = fs.Read(tailBytes, 0, headTailSize);
                    if (tailRead < headTailSize)
                        Array.Resize(ref tailBytes, tailRead);
                }
                else
                {
                    tailBytes = Array.Empty<byte>();
                }
            }

            // Search for byte patterns in header/trailer only
            foreach (var pattern in RawBytePatterns)
            {
                if (ContainsPattern(headBytes, pattern) || ContainsPattern(tailBytes, pattern))
                {
                    string patternStr = Encoding.ASCII.GetString(pattern);
                    string source = CategorizeMarker(patternStr);
                    if (!string.IsNullOrEmpty(source))
                        found.Add(source);
                }
            }

            // Search for text patterns in header/trailer only (not audio data)
            string headText = Encoding.ASCII.GetString(headBytes).ToLowerInvariant();
            string tailText = tailBytes.Length > 0
                ? Encoding.ASCII.GetString(tailBytes).ToLowerInvariant()
                : "";

            foreach (var pattern in RawTextPatterns)
            {
                if (headText.Contains(pattern) || tailText.Contains(pattern))
                {
                    string source = CategorizeMarker(pattern);
                    if (!string.IsNullOrEmpty(source))
                        found.Add(source);
                }
            }
        }

        // ══════════════════════════════════════════════════════════════
        //  Helpers
        // ══════════════════════════════════════════════════════════════

        private static void AppendIfNotEmpty(StringBuilder sb, string key, string? value)
        {
            if (!string.IsNullOrWhiteSpace(value))
                sb.Append(' ').Append(key).Append(':').Append(value);
        }

        /// <summary>
        /// Maps a detected marker string to a human-readable source name.
        /// </summary>
        private static string CategorizeMarker(string marker)
        {
            var lower = marker.ToLowerInvariant();

            // Use specific domain matches to avoid false positives.
            // "udio" alone matches "audio"/"studio" — require "udio.com" or "udio.ai".
            if (lower.Contains("suno.ai") || lower.Contains("suno.com")) return "Suno AI";
            if (lower.Contains("udio.com")) return "Udio";
            if (lower.Contains("soundraw")) return "Soundraw";
            if (lower.Contains("aiva.ai")) return "AIVA";
            if (lower.Contains("boomy.com")) return "Boomy";
            if (lower.Contains("amper music") || lower.Contains("shutterstock ai")) return "Amper/Shutterstock";
            if (lower.Contains("loudly.com")) return "Loudly";
            if (lower.Contains("beatoven")) return "Beatoven.ai";
            if (lower.Contains("mubert")) return "Mubert";
            if (lower.Contains("stable audio") || lower.Contains("stability.ai")) return "Stable Audio";
            if (lower.Contains("riffusion")) return "Riffusion";
            if (lower.Contains("musiclm")) return "MusicLM";
            if (lower.Contains("musicgen")) return "MusicGen";
            if (lower.Contains("audiogen")) return "AudioGen";
            if (lower.Contains("openai jukebox")) return "OpenAI Jukebox";
            if (lower.Contains("audioseal") || lower.Contains("audio_seal")) return "AudioSeal Watermark";
            if (lower.Contains("synthid") || lower.Contains("synth_id")) return "SynthID Watermark";
            if (lower.Contains("wavmark") || lower.Contains("wav_mark")) return "WavMark Watermark";
            if (lower.Contains("contentcredential") || lower.Contains("content credential")) return "Content Credentials";
            if (lower.Contains("contentauthenticity") || lower.Contains("content authenticity")) return "Content Authenticity";
            if (lower.Contains("ai-generated") || lower.Contains("ai_generated")) return "AI Generated";
            if (lower.Contains("generated by ai") || lower.Contains("created by ai") || lower.Contains("made by ai")) return "AI Generated";

            return "AI Marker Found";
        }

        /// <summary>
        /// Searches for a byte pattern within a buffer (simple KMP-like search).
        /// </summary>
        private static bool ContainsPattern(byte[] buffer, byte[] pattern)
        {
            if (pattern.Length == 0 || buffer.Length < pattern.Length) return false;

            for (int i = 0; i <= buffer.Length - pattern.Length; i++)
            {
                bool match = true;
                for (int j = 0; j < pattern.Length; j++)
                {
                    if (buffer[i + j] != pattern[j])
                    {
                        match = false;
                        break;
                    }
                }
                if (match) return true;
            }
            return false;
        }
    }
}
