using System;
using System.Collections.Generic;

namespace AudioQualityChecker.Theming
{
    /// <summary>
    /// The built-in colour palettes, as ARGB hex, shared by every UI that draws them.
    ///
    /// These values used to be duplicated by hand in the WPF and Avalonia theme managers,
    /// and had already drifted apart in 8 of the 10 themes. Keeping one copy here means the
    /// two front-ends can differ in how they render a colour but never in which colour it is.
    /// Each front-end converts these to its own brush type; nothing UI-specific lives here.
    /// </summary>
    public static class ThemePalettes
    {
        public const string DefaultTheme = "Dark";

        /// <summary>Built-in theme names, in the order they are offered to the user.</summary>
        public static IReadOnlyList<string> Names { get; } = new[]
        {
            "Dark", "Ocean", "Light", "Amethyst", "Dreamsicle", "Goldenrod", "Emerald", "Blurple", "Crimson", "Brown"
        };

        /// <summary>The colour roles every palette defines.</summary>
        public static IReadOnlyList<string> Keys { get; } = new[]
        {
            "WindowBg", "PanelBg", "ToolbarBg", "HeaderBg",
            "GridBg", "GridRowBg", "GridAltRowBg", "BorderColor",
            "InputBg", "SelectionBg", "ButtonBg", "ButtonBorder",
            "ButtonHover", "ButtonPressed", "AccentColor", "TextPrimary",
            "TextSecondary", "TextMuted", "TextDim", "ScrollBg",
            "ScrollThumb", "ScrollThumbHover", "GridLineColor", "RowHoverBg",
            "SplitterBg", "ProgressBg",
        };

        /// <summary>
        /// The palette for <paramref name="theme"/>, or the Dark palette when the name is
        /// unknown — matching the WPF switch expression this was extracted from.
        /// </summary>
        public static IReadOnlyDictionary<string, string> Get(string? theme) =>
            theme is not null && All.TryGetValue(theme, out var palette) ? palette : All[DefaultTheme];

        public static bool IsBuiltIn(string? theme) =>
            theme is not null && All.ContainsKey(theme);

        /// <summary>Every built-in palette, keyed by theme name (case-insensitive).</summary>
        public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> All { get; } =
            new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
            {
                ["Dark"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1E1E1E",
                    ["PanelBg"]             = "#FF181818",
                    ["ToolbarBg"]           = "#FF2D2D30",
                    ["HeaderBg"]            = "#FF333337",
                    ["GridBg"]              = "#FF181818",
                    ["GridRowBg"]           = "#FF1E1E1E",
                    ["GridAltRowBg"]        = "#FF252526",
                    ["BorderColor"]         = "#FF3F3F46",
                    ["InputBg"]             = "#FF2A2A2E",
                    ["SelectionBg"]         = "#FF264F78",
                    ["ButtonBg"]            = "#FF3C3C3C",
                    ["ButtonBorder"]        = "#FF555555",
                    ["ButtonHover"]         = "#FF505050",
                    ["ButtonPressed"]       = "#FF007ACC",
                    ["AccentColor"]         = "#FF007ACC",
                    ["TextPrimary"]         = "#FFD4D4D4",
                    ["TextSecondary"]       = "#FFB0B0B0",
                    ["TextMuted"]           = "#FF888888",
                    ["TextDim"]             = "#FF555555",
                    ["ScrollBg"]            = "#FF2A2A2E",
                    ["ScrollThumb"]         = "#FF686868",
                    ["ScrollThumbHover"]    = "#FF888888",
                    ["GridLineColor"]       = "#FF2A2A2E",
                    ["RowHoverBg"]          = "#FF2A2D2E",
                    ["SplitterBg"]          = "#FF2D2D30",
                    ["ProgressBg"]          = "#FF333337",
                },
                ["Ocean"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF0D1B2A",
                    ["PanelBg"]             = "#FF0A1628",
                    ["ToolbarBg"]           = "#FF132238",
                    ["HeaderBg"]            = "#FF1A2D47",
                    ["GridBg"]              = "#FF0A1628",
                    ["GridRowBg"]           = "#FF0D1B2A",
                    ["GridAltRowBg"]        = "#FF112240",
                    ["BorderColor"]         = "#FF1E3A5F",
                    ["InputBg"]             = "#FF0F1D30",
                    ["SelectionBg"]         = "#FF1A4B7A",
                    ["ButtonBg"]            = "#FF162D4A",
                    ["ButtonBorder"]        = "#FF1E3A5F",
                    ["ButtonHover"]         = "#FF1E4468",
                    ["ButtonPressed"]       = "#FF4DA8DA",
                    ["AccentColor"]         = "#FF4DA8DA",
                    ["TextPrimary"]         = "#FFD0E4F5",
                    ["TextSecondary"]       = "#FF8BB8D6",
                    ["TextMuted"]           = "#FF5A8AAD",
                    ["TextDim"]             = "#FF2E5070",
                    ["ScrollBg"]            = "#FF0F1D30",
                    ["ScrollThumb"]         = "#FF3A6080",
                    ["ScrollThumbHover"]    = "#FF4A7898",
                    ["GridLineColor"]       = "#FF152A42",
                    ["RowHoverBg"]          = "#FF142838",
                    ["SplitterBg"]          = "#FF132238",
                    ["ProgressBg"]          = "#FF162D4A",
                },
                ["Light"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FFF5F5F5",
                    ["PanelBg"]             = "#FFFFFFFF",
                    ["ToolbarBg"]           = "#FFE8E8EC",
                    ["HeaderBg"]            = "#FFDCDCE0",
                    ["GridBg"]              = "#FFFFFFFF",
                    ["GridRowBg"]           = "#FFFFFFFF",
                    ["GridAltRowBg"]        = "#FFF8F8FA",
                    ["BorderColor"]         = "#FFCCCCCC",
                    ["InputBg"]             = "#FFFFFFFF",
                    ["SelectionBg"]         = "#FF0078D4",
                    ["ButtonBg"]            = "#FFE1E1E1",
                    ["ButtonBorder"]        = "#FFBBBBBB",
                    ["ButtonHover"]         = "#FFD0D0D0",
                    ["ButtonPressed"]       = "#FF0078D4",
                    ["AccentColor"]         = "#FF0078D4",
                    ["TextPrimary"]         = "#FF1E1E1E",
                    ["TextSecondary"]       = "#FF444444",
                    ["TextMuted"]           = "#FF666666",
                    ["TextDim"]             = "#FF777777",
                    ["ScrollBg"]            = "#FFE8E8E8",
                    ["ScrollThumb"]         = "#FFA0A0A0",
                    ["ScrollThumbHover"]    = "#FF808080",
                    ["GridLineColor"]       = "#FFE0E0E0",
                    ["RowHoverBg"]          = "#FFEAF1FB",
                    ["SplitterBg"]          = "#FFDCDCE0",
                    ["ProgressBg"]          = "#FFE0E0E0",
                },
                ["Amethyst"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1A1228",
                    ["PanelBg"]             = "#FF150E22",
                    ["ToolbarBg"]           = "#FF221838",
                    ["HeaderBg"]            = "#FF2C2044",
                    ["GridBg"]              = "#FF150E22",
                    ["GridRowBg"]           = "#FF1A1228",
                    ["GridAltRowBg"]        = "#FF201638",
                    ["BorderColor"]         = "#FF3D2A5C",
                    ["InputBg"]             = "#FF1E142E",
                    ["SelectionBg"]         = "#FF5A2E8C",
                    ["ButtonBg"]            = "#FF2A1E42",
                    ["ButtonBorder"]        = "#FF4A3468",
                    ["ButtonHover"]         = "#FF3A2858",
                    ["ButtonPressed"]       = "#FF8B5CF6",
                    ["AccentColor"]         = "#FF8B5CF6",
                    ["TextPrimary"]         = "#FFE0D4F5",
                    ["TextSecondary"]       = "#FFB8A0D6",
                    ["TextMuted"]           = "#FF7860A0",
                    ["TextDim"]             = "#FF463060",
                    ["ScrollBg"]            = "#FF1E142E",
                    ["ScrollThumb"]         = "#FF5A4480",
                    ["ScrollThumbHover"]    = "#FF7860A0",
                    ["GridLineColor"]       = "#FF251A3A",
                    ["RowHoverBg"]          = "#FF241A36",
                    ["SplitterBg"]          = "#FF221838",
                    ["ProgressBg"]          = "#FF2A1E42",
                },
                ["Dreamsicle"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1F1510",
                    ["PanelBg"]             = "#FF1A120C",
                    ["ToolbarBg"]           = "#FF2E1E14",
                    ["HeaderBg"]            = "#FF3A2818",
                    ["GridBg"]              = "#FF1A120C",
                    ["GridRowBg"]           = "#FF1F1510",
                    ["GridAltRowBg"]        = "#FF2A1C12",
                    ["BorderColor"]         = "#FF5A3820",
                    ["InputBg"]             = "#FF241A12",
                    ["SelectionBg"]         = "#FF8B4513",
                    ["ButtonBg"]            = "#FF352414",
                    ["ButtonBorder"]        = "#FF6B4228",
                    ["ButtonHover"]         = "#FF45301C",
                    ["ButtonPressed"]       = "#FFFF8C42",
                    ["AccentColor"]         = "#FFFF8C42",
                    ["TextPrimary"]         = "#FFF5E0CC",
                    ["TextSecondary"]       = "#FFD6A87A",
                    ["TextMuted"]           = "#FF9A7050",
                    ["TextDim"]             = "#FF5A3E28",
                    ["ScrollBg"]            = "#FF241A12",
                    ["ScrollThumb"]         = "#FF7A5030",
                    ["ScrollThumbHover"]    = "#FF9A6840",
                    ["GridLineColor"]       = "#FF2E1E14",
                    ["RowHoverBg"]          = "#FF2E2014",
                    ["SplitterBg"]          = "#FF2E1E14",
                    ["ProgressBg"]          = "#FF352414",
                },
                ["Goldenrod"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1E1C0E",
                    ["PanelBg"]             = "#FF1A180A",
                    ["ToolbarBg"]           = "#FF383010",
                    ["HeaderBg"]            = "#FF4A4018",
                    ["GridBg"]              = "#FF1A180A",
                    ["GridRowBg"]           = "#FF1E1C0E",
                    ["GridAltRowBg"]        = "#FF2E2810",
                    ["BorderColor"]         = "#FF6B5A18",
                    ["InputBg"]             = "#FF262010",
                    ["SelectionBg"]         = "#FF9A8010",
                    ["ButtonBg"]            = "#FF3E3510",
                    ["ButtonBorder"]        = "#FF7A6820",
                    ["ButtonHover"]         = "#FF504618",
                    ["ButtonPressed"]       = "#FFE8B811",
                    ["AccentColor"]         = "#FFE8B811",
                    ["TextPrimary"]         = "#FFF5ECCC",
                    ["TextSecondary"]       = "#FFDCC680",
                    ["TextMuted"]           = "#FFAA9445",
                    ["TextDim"]             = "#FF6A5828",
                    ["ScrollBg"]            = "#FF262010",
                    ["ScrollThumb"]         = "#FF8A7428",
                    ["ScrollThumbHover"]    = "#FFAA9438",
                    ["GridLineColor"]       = "#FF322C10",
                    ["RowHoverBg"]          = "#FF322C14",
                    ["SplitterBg"]          = "#FF383010",
                    ["ProgressBg"]          = "#FF3E3510",
                },
                ["Emerald"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF0F1C14",
                    ["PanelBg"]             = "#FF0A1810",
                    ["ToolbarBg"]           = "#FF14281C",
                    ["HeaderBg"]            = "#FF1A3424",
                    ["GridBg"]              = "#FF0A1810",
                    ["GridRowBg"]           = "#FF0F1C14",
                    ["GridAltRowBg"]        = "#FF12241A",
                    ["BorderColor"]         = "#FF1E5A3A",
                    ["InputBg"]             = "#FF0E2018",
                    ["SelectionBg"]         = "#FF1A7A4A",
                    ["ButtonBg"]            = "#FF162D20",
                    ["ButtonBorder"]        = "#FF1E5A3A",
                    ["ButtonHover"]         = "#FF1E4430",
                    ["ButtonPressed"]       = "#FF2ECC71",
                    ["AccentColor"]         = "#FF2ECC71",
                    ["TextPrimary"]         = "#FFD0F5E0",
                    ["TextSecondary"]       = "#FF8BD6AA",
                    ["TextMuted"]           = "#FF5AAD7A",
                    ["TextDim"]             = "#FF2E7050",
                    ["ScrollBg"]            = "#FF0E2018",
                    ["ScrollThumb"]         = "#FF3A8060",
                    ["ScrollThumbHover"]    = "#FF4A9870",
                    ["GridLineColor"]       = "#FF142A1E",
                    ["RowHoverBg"]          = "#FF142820",
                    ["SplitterBg"]          = "#FF14281C",
                    ["ProgressBg"]          = "#FF162D20",
                },
                ["Blurple"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1E1F3B",
                    ["PanelBg"]             = "#FF1A1B36",
                    ["ToolbarBg"]           = "#FF2C2D56",
                    ["HeaderBg"]            = "#FF353668",
                    ["GridBg"]              = "#FF1A1B36",
                    ["GridRowBg"]           = "#FF1E1F3B",
                    ["GridAltRowBg"]        = "#FF272850",
                    ["BorderColor"]         = "#FF4A4B8A",
                    ["InputBg"]             = "#FF222344",
                    ["SelectionBg"]         = "#FF4752C4",
                    ["ButtonBg"]            = "#FF30325E",
                    ["ButtonBorder"]        = "#FF5865F2",
                    ["ButtonHover"]         = "#FF3D3F76",
                    ["ButtonPressed"]       = "#FF7289DA",
                    ["AccentColor"]         = "#FF5865F2",
                    ["TextPrimary"]         = "#FFE0E1FF",
                    ["TextSecondary"]       = "#FFA5A7D4",
                    ["TextMuted"]           = "#FF7375B0",
                    ["TextDim"]             = "#FF464878",
                    ["ScrollBg"]            = "#FF222344",
                    ["ScrollThumb"]         = "#FF5865F2",
                    ["ScrollThumbHover"]    = "#FF7289DA",
                    ["GridLineColor"]       = "#FF2A2B50",
                    ["RowHoverBg"]          = "#FF2E2F58",
                    ["SplitterBg"]          = "#FF2C2D56",
                    ["ProgressBg"]          = "#FF30325E",
                },
                ["Crimson"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1E1012",
                    ["PanelBg"]             = "#FF180C0E",
                    ["ToolbarBg"]           = "#FF2E1418",
                    ["HeaderBg"]            = "#FF3A1C22",
                    ["GridBg"]              = "#FF180C0E",
                    ["GridRowBg"]           = "#FF1E1012",
                    ["GridAltRowBg"]        = "#FF281418",
                    ["BorderColor"]         = "#FF5A2030",
                    ["InputBg"]             = "#FF221014",
                    ["SelectionBg"]         = "#FF8B1A2A",
                    ["ButtonBg"]            = "#FF351820",
                    ["ButtonBorder"]        = "#FF6B2838",
                    ["ButtonHover"]         = "#FF452028",
                    ["ButtonPressed"]       = "#FFDC143C",
                    ["AccentColor"]         = "#FFDC143C",
                    ["TextPrimary"]         = "#FFF5D0D4",
                    ["TextSecondary"]       = "#FFD6909A",
                    ["TextMuted"]           = "#FF9A5060",
                    ["TextDim"]             = "#FF5A2838",
                    ["ScrollBg"]            = "#FF221014",
                    ["ScrollThumb"]         = "#FF7A3040",
                    ["ScrollThumbHover"]    = "#FF9A4050",
                    ["GridLineColor"]       = "#FF2E1418",
                    ["RowHoverBg"]          = "#FF2E1820",
                    ["SplitterBg"]          = "#FF2E1418",
                    ["ProgressBg"]          = "#FF351820",
                },
                ["Brown"] = new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["WindowBg"]            = "#FF1E1810",
                    ["PanelBg"]             = "#FF1A140E",
                    ["ToolbarBg"]           = "#FF2E2216",
                    ["HeaderBg"]            = "#FF3A2C1E",
                    ["GridBg"]              = "#FF1A140E",
                    ["GridRowBg"]           = "#FF1E1810",
                    ["GridAltRowBg"]        = "#FF281E14",
                    ["BorderColor"]         = "#FF5A4228",
                    ["InputBg"]             = "#FF221A12",
                    ["SelectionBg"]         = "#FF7A5830",
                    ["ButtonBg"]            = "#FF352818",
                    ["ButtonBorder"]        = "#FF6B4E2E",
                    ["ButtonHover"]         = "#FF453420",
                    ["ButtonPressed"]       = "#FFC08040",
                    ["AccentColor"]         = "#FFC08040",
                    ["TextPrimary"]         = "#FFF0E0CC",
                    ["TextSecondary"]       = "#FFD0B08A",
                    ["TextMuted"]           = "#FF907050",
                    ["TextDim"]             = "#FF584030",
                    ["ScrollBg"]            = "#FF221A12",
                    ["ScrollThumb"]         = "#FF7A5A38",
                    ["ScrollThumbHover"]    = "#FF9A7048",
                    ["GridLineColor"]       = "#FF2A2014",
                    ["RowHoverBg"]          = "#FF2E2218",
                    ["SplitterBg"]          = "#FF2E2216",
                    ["ProgressBg"]          = "#FF352818",
                },
            };
    }
}
