# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Angel.AudioAuditor
PackageVersion: 1.4.2
InstallerLocale: en-US
InstallerType: portable
InstallModes:
  - silent
  - silentWithProgress
  - interactive
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Angel2mp3/AudioAuditor/releases/download/v1.4.2/AudioAuditor.exe
    InstallerSha256: 45F349B44D8ED7CD6C5A2EF05F120C3A0E2E9598F7A84ABD4E9F217CEEB4E450
    Commands:
      - AudioAuditor
    InstallScope: user
ManifestType: installer
ManifestVersion: 1.6.0
