# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Angel.AudioAuditorCLI
PackageVersion: 1.5.1
InstallerLocale: en-US
InstallerType: portable
InstallModes:
  - silent
  - silentWithProgress
  - interactive
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Angel2mp3/AudioAuditor/releases/download/v1.5.1/AudioAuditorCLI.exe
    InstallerSha256: C13BA62A318B714DC623BAF83EFF821A88B811C78CD00F3BA0840B665A5D3023
    Commands:
      - AudioAuditorCLI
    InstallScope: user
ManifestType: installer
ManifestVersion: 1.6.0
