# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Angel.AudioAuditorCLI
PackageVersion: 1.7.0
InstallerLocale: en-US
InstallerType: portable
InstallModes:
  - silent
  - silentWithProgress
  - interactive
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Angel2mp3/AudioAuditor/releases/download/v1.7.0/AudioAuditorCLI.exe
    InstallerSha256: 4CE2B28667B5FD8FEEB7F3205CDAA1266C49CE7386E5750E929F047255EE9477
    Commands:
      - AudioAuditorCLI
    InstallScope: user
ManifestType: installer
ManifestVersion: 1.6.0
